dist: xenial # Required for Python >= 3.7
language: python
branches:
  only:
    - master
    - dev
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install pandas
  - pip install matplotlib
  - pip install .
script: python -m test_data_tools
